### ISSUE TITLE
Not working with use_frameworks! :linkage => :static  (Expo 51 & RN 0.74.3)

### ISSUE THREAD

**Issue by AChevallier** [rive-app/rive-react-native#261]
I am upgrading from expo 50 to expo 51 with `  "rive-react-native": "7.3.0"` 
My builds on android & ios are working. 
Everything is working well on android.

after a successful  `eas build -p ios --profile simulator --local --clear-cache`, I start the app and it crashes.
I can see ` 0x10e7cc000 -        0x10eceffff rive.app.ios.runtime.RiveRuntime (5.14.0)` in the crash.

I tried to remove `rive-react-native` from my app & it worked

Has anyone managed to get it to work on Expo 51? 
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 1
CrashReporter Key:   1
Hardware Model:      MacBookPro18,3
Process:             XXXXX [7197]
Path:                XXX
Identifier:          XXX
Version:             1.0.0 (1)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [6362]
Coalition:           com.apple.CoreSimulator.SimDevice.CF22F361-AC78-4974-98D5-436C32776898 [51711]
Responsible Process: SimulatorTrampoline [5943]

Date/Time:           2024-08-05 12:34:18.8075 +0100
Launch Time:         2024-08-05 12:33:04.2247 +0100
OS Version:          macOS 15.0 (24A5298h)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000104100
Exception Codes: 0x0000000000000001, 0x0000000000104100
VM Region Info: 0x104100 is not in any region.  Bytes before following region: 4327571200
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10201c000-105b6c000    [ 59.3M] r-x/r-x SM=COW  /Users/USER/Library/Developer/CoreSimulator/Devices/CF22F361-AC78-4974-98D5-436C32776898/data/Containers/Bundle/Application/2E347A4B-7D9F-4534-9B53-D8E4ADCAA538/XXXXX.app/XXXXX
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [7197]

Triggered by Thread:  3

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x10d3a9290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x10d3ba6c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10d3b13f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x10d3a95cc mach_msg + 20
4   CoreFoundation                	       0x18040e684 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180408d64 __CFRunLoopRun + 1148
6   CoreFoundation                	       0x1804084d4 CFRunLoopRunSpecific + 572
7   GraphicsServices              	       0x18ef2aae4 GSEventRunModal + 160
8   UIKitCore                     	       0x1853d0a28 -[UIApplication _run] + 868
9   UIKitCore                     	       0x1853d46b0 UIApplicationMain + 124
10  XXXXX                       	       0x102021e0c main + 96
11  dyld_sim                      	       0x10d1e1544 start_sim + 20
12  dyld                          	       0x10d432274 start + 2840

Thread 1:
0   libsystem_pthread.dylib       	       0x10d14692c start_wqthread + 0

Thread 2:: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib        	       0x10d3a9290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x10d3ba6c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10d3b13f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x10d3a95cc mach_msg + 20
4   CoreFoundation                	       0x18040e684 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180408d64 __CFRunLoopRun + 1148
6   CoreFoundation                	       0x1804084d4 CFRunLoopRunSpecific + 572
7   Foundation                    	       0x180dd340c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 208
8   Foundation                    	       0x180dd3630 -[NSRunLoop(NSRunLoop) runUntilDate:] + 60
9   UIKitCore                     	       0x1854773f8 -[UIEventFetcher threadMain] + 404
10  Foundation                    	       0x180df9c64 __NSThread__start__ + 720
11  libsystem_pthread.dylib       	       0x10d14b6f8 _pthread_start + 104
12  libsystem_pthread.dylib       	       0x10d146940 thread_start + 8

Thread 3 Crashed::  Dispatch queue: com.facebook.react.ShadowQueue
0   ???                           	          0x104100 ???
1   XXXXX                       	       0x10366b728 -[RCTShadowView layoutWithMinimumSize:maximumSize:layoutDirection:layoutContext:] + 176
2   XXXXX                       	       0x1036598e0 -[RCTRootShadowView layoutWithAffectedShadowViews:] + 248
3   XXXXX                       	       0x10367f3cc -[RCTUIManager uiBlockWithLayoutUpdateForRootView:] + 344
4   XXXXX                       	       0x103684de4 -[RCTUIManager _layoutAndMount] + 336
5   XXXXX                       	       0x103684c88 -[RCTUIManager batchDidComplete] + 32
6   XXXXX                       	       0x1035d5b64 __32-[RCTCxxBridge batchDidComplete]_block_invoke + 56
7   libdispatch.dylib             	       0x180170104 _dispatch_call_block_and_release + 24
8   libdispatch.dylib             	       0x180171978 _dispatch_client_callout + 16
9   libdispatch.dylib             	       0x180179b10 _dispatch_lane_serial_drain + 960
10  libdispatch.dylib             	       0x18017a688 _dispatch_lane_invoke + 388
11  libdispatch.dylib             	       0x180185a84 _dispatch_root_queue_drain_deferred_wlh + 276
12  libdispatch.dylib             	       0x1801850d0 _dispatch_workloop_worker_thread + 448
13  libsystem_pthread.dylib       	       0x10d147b74 _pthread_wqthread + 284
14  libsystem_pthread.dylib       	       0x10d146934 start_wqthread + 8

Thread 4:: com.apple.CFNetwork.CustomProtocols
0   libsystem_kernel.dylib        	       0x10d3a9290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x10d3ba6c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10d3b13f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x10d3a95cc mach_msg + 20
4   CoreFoundation                	       0x18040e684 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180408d64 __CFRunLoopRun + 1148
6   CoreFoundation                	       0x1804084d4 CFRunLoopRunSpecific + 572
7   CFNetwork                     	       0x184526cd8 0x18430f000 + 2194648
8   Foundation                    	       0x180df9c64 __NSThread__start__ + 720
9   libsystem_pthread.dylib       	       0x10d14b6f8 _pthread_start + 104
10  libsystem_pthread.dylib       	       0x10d146940 thread_start + 8

Thread 5:: com.facebook.SocketRocket.NetworkThread
0   libsystem_kernel.dylib        	       0x10d3a9290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x10d3ba6c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10d3b13f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x10d3a95cc mach_msg + 20
4   CoreFoundation                	       0x18040e684 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180408d64 __CFRunLoopRun + 1148
6   CoreFoundation                	       0x1804084d4 CFRunLoopRunSpecific + 572
7   Foundation                    	       0x180dd340c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 208
8   XXXXX                       	       0x103fa7978 -[SRRunLoopThread main] + 260
9   Foundation                    	       0x180df9c64 __NSThread__start__ + 720
10  libsystem_pthread.dylib       	       0x10d14b6f8 _pthread_start + 104
11  libsystem_pthread.dylib       	       0x10d146940 thread_start + 8

Thread 6:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	       0x10d3a9290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x10d3ba6c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10d3b13f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x10d3a95cc mach_msg + 20
4   CoreFoundation                	       0x18040e684 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180408d64 __CFRunLoopRun + 1148
6   CoreFoundation                	       0x1804084d4 CFRunLoopRunSpecific + 572
7   CFNetwork                     	       0x184526cd8 0x18430f000 + 2194648
8   Foundation                    	       0x180df9c64 __NSThread__start__ + 720
9   libsystem_pthread.dylib       	       0x10d14b6f8 _pthread_start + 104
10  libsystem_pthread.dylib       	       0x10d146940 thread_start + 8

Thread 7:: com.facebook.react.JavaScript
0   libsystem_malloc.dylib        	       0x1801d79c4 _free + 48
1   libobjc.A.dylib               	       0x180086ddc AutoreleasePoolPage::releaseUntil(objc_object**) + 220
2   libobjc.A.dylib               	       0x180086c98 objc_autoreleasePoolPop + 256
3   XXXXX                       	       0x10361da9c invocation function for block in facebook::react::RCTMessageThread::runAsync(std::__1::function<void ()>) + 56
4   CoreFoundation                	       0x18040ec10 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
5   CoreFoundation                	       0x18040e358 __CFRunLoopDoBlocks + 352
6   CoreFoundation                	       0x180409224 __CFRunLoopRun + 2364
7   CoreFoundation                	       0x1804084d4 CFRunLoopRunSpecific + 572
8   XXXXX                       	       0x1035c8c48 +[RCTCxxBridge runRunLoop] + 736
9   Foundation                    	       0x180df9c64 __NSThread__start__ + 720
10  libsystem_pthread.dylib       	       0x10d14b6f8 _pthread_start + 104
11  libsystem_pthread.dylib       	       0x10d146940 thread_start + 8

Thread 8:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	       0x10d3b3700 __select + 8
1   CoreFoundation                	       0x18041d06c __CFSocketManager + 612
2   libsystem_pthread.dylib       	       0x10d14b6f8 _pthread_start + 104
3   libsystem_pthread.dylib       	       0x10d146940 thread_start + 8

Thread 9:: hades
0   libsystem_kernel.dylib        	       0x10d3ac72c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x10d14bc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x1802ea6d8 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   hermes                        	       0x10f002448 hermes::vm::HadesGC::Executor::worker() + 112
4   hermes                        	       0x10f0023ac void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, hermes::vm::HadesGC::Executor::Executor()::'lambda'()>>(void*) + 44
5   libsystem_pthread.dylib       	       0x10d14b6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x10d146940 thread_start + 8

Thread 10:
0   libsystem_pthread.dylib       	       0x10d14692c start_wqthread + 0

Thread 11:
0   libsystem_pthread.dylib       	       0x10d14692c start_wqthread + 0

Thread 12:: com.apple.CFStream.LegacyThread
0   libsystem_kernel.dylib        	       0x10d3a9290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x10d3ba6c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10d3b13f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x10d3a95cc mach_msg + 20
4   CoreFoundation                	       0x18040e684 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180408d64 __CFRunLoopRun + 1148
6   CoreFoundation                	       0x1804084d4 CFRunLoopRunSpecific + 572
7   CoreFoundation                	       0x18042bd80 _legacyStreamRunLoop_workThread + 260
8   libsystem_pthread.dylib       	       0x10d14b6f8 _pthread_start + 104
9   libsystem_pthread.dylib       	       0x10d146940 thread_start + 8

Thread 13:
0   libsystem_pthread.dylib       	       0x10d14692c start_wqthread + 0

Thread 14:
0   libsystem_pthread.dylib       	       0x10d14692c start_wqthread + 0


Thread 3 crashed with ARM Thread State (64-bit):
    x0: 0x000000010da1ab30   x1: 0x0000000000104100   x2: 0x000000007f8f0f0f   x3: 0x000000016e099fa0
    x4: 0x0000000000000004   x5: 0x0000000000000000   x6: 0x0000000000000072   x7: 0x0000000000000000
    x8: 0x0000000000000014   x9: 0x0000000000000004  x10: 0x00000001036182dc  x11: 0x0000000000000001
   x12: 0x0000000020000001  x13: 0x0000000100000000  x14: 0x0000000100000000  x15: 0x0000000300000000
   x16: 0x000000010ec4bf80  x17: 0x000000010366b678  x18: 0x0000000000000000  x19: 0x000000010da1ab30
   x20: 0x000000007fc00000  x21: 0x0000000000000114  x22: 0x0000000000000004  x23: 0x0000000000000000
   x24: 0x0000600002c285e8  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000600001846c00
   x28: 0x0000000000000000   fp: 0x000000016e099d30   lr: 0x000000010ec49d30
    sp: 0x000000016e099d20   pc: 0x0000000000104100 cpsr: 0x20001000
   far: 0x0000000000104100  esr: 0x82000006 (Instruction Abort) Translation fault

Binary Images:
       0x10d42c000 -        0x10d4affff dyld (*) <080914bd-cd81-3697-869a-d72be1cf17a1> /usr/lib/dyld
       0x10d418000 -        0x10d423fff libobjc-trampolines.dylib (*) <c6ef2cc0-8ca9-3a69-a525-91bec719ddfc> /Volumes/VOLUME/*/libobjc-trampolines.dylib
       0x10e7cc000 -        0x10eceffff rive.app.ios.runtime.RiveRuntime (5.14.0) <1083a49d-e909-32bd-8c2b-65dc470d605d> /Users/USER/Library/Developer/CoreSimulator/Devices/CF22F361-AC78-4974-98D5-436C32776898/data/Containers/Bundle/Application/2E347A4B-7D9F-4534-9B53-D8E4ADCAA538/XXXXX.app/Frameworks/RiveRuntime.framework/RiveRuntime
       0x10ee9c000 -        0x10f1a3fff dev.hermesengine.iphonesimulator (0.12.0) <da1e35b7-50d8-30f1-9c8f-759f09716be4> /Users/USER/Library/Developer/CoreSimulator/Devices/CF22F361-AC78-4974-98D5-436C32776898/data/Containers/Bundle/Application/2E347A4B-7D9F-4534-9B53-D8E4ADCAA538/XXXXX.app/Frameworks/hermes.framework/hermes
       0x10d1a0000 -        0x10d1a7fff libsystem_platform.dylib (*) <f10d409f-99af-3916-bf8f-af8bddcf5af6> /usr/lib/system/libsystem_platform.dylib
       0x10d3a8000 -        0x10d3e3fff libsystem_kernel.dylib (*) <51d14057-5ba5-314d-adac-1bd3afb55651> /usr/lib/system/libsystem_kernel.dylib
       0x10d144000 -        0x10d153fff libsystem_pthread.dylib (*) <a3ce76a2-e7e7-38a5-80e1-1c5ada47cc9a> /usr/lib/system/libsystem_pthread.dylib
       0x10201c000 -        0x105b6bfff com.XXXXX.app (1.9.4) <c4e998be-b328-3dfc-bfb4-7315415cd5d9> /Users/USER/Library/Developer/CoreSimulator/Devices/CF22F361-AC78-4974-98D5-436C32776898/data/Containers/Bundle/Application/2E347A4B-7D9F-4534-9B53-D8E4ADCAA538/XXXXX.app/XXXXX
       0x10d1e0000 -        0x10d22bfff dyld_sim (*) <f1d509a4-edf1-3668-b217-c6a2bd1fbef4> /Volumes/VOLUME/*/dyld_sim
       0x180381000 -        0x180734fff com.apple.CoreFoundation (6.9) <6c40f9e5-bffa-3413-9e1c-a4f724ad56ba> /Volumes/VOLUME/*/CoreFoundation.framework/CoreFoundation
       0x18ef27000 -        0x18ef2ffff com.apple.GraphicsServices (1.0) <b8bade4e-4da1-3e89-aadc-79d9356e07f1> /Volumes/VOLUME/*/GraphicsServices.framework/GraphicsServices
       0x1847df000 -        0x186186fff com.apple.UIKitCore (1.0) <8d3f22bc-9dec-3601-b822-2b88624be742> /Volumes/VOLUME/*/UIKitCore.framework/UIKitCore
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x1807b4000 -        0x181264fff com.apple.Foundation (6.9) <3a54db51-8b3a-308d-9f9e-51474c4a8520> /Volumes/VOLUME/*/Foundation.framework/Foundation
       0x18016e000 -        0x1801b3fff libdispatch.dylib (*) <b8c72eee-14e7-3c88-ae33-a9bf80378af5> /Volumes/VOLUME/*/libdispatch.dylib
       0x18430f000 -        0x1846a0fff com.apple.CFNetwork (1.0) <ad068dfd-5acf-3c3f-9449-adf0b044e328> /Volumes/VOLUME/*/CFNetwork.framework/CFNetwork
       0x1801b4000 -        0x1801edff7 libsystem_malloc.dylib (*) <a0a72526-44d3-3607-b245-be9351888fb9> /Volumes/VOLUME/*/libsystem_malloc.dylib
       0x18005c000 -        0x180098d93 libobjc.A.dylib (*) <78996745-4c54-3f78-b78d-e21931453c5a> /Volumes/VOLUME/*/libobjc.A.dylib
       0x1802da000 -        0x18035bfff libc++.1.dylib (*) <27a11d15-9506-3776-8d00-9f34bea3ecb1> /Volumes/VOLUME/*/libc++.1.dylib

EOF

```

**Comment by mrcool-ru** [comment]
I have the same issue if I use `use_frameworks! :linkage => :static` in Podfile
Works fine without use_frameworks

**Comment by DevYuns** [comment]
I encountered a similar issue on ios. The build works fine in debug mode, but the IOS app crashes on startup with version `7.3.0`. Android is ok.

**Comment by JslinSir** [comment]
+1

**Comment by Thylacine-Software** [comment]
Same happening to me. It seems that use-frameworks is not compatible with latest 7.3.0 version.

**Comment by lancesnider** [comment]
Thanks for reporting this! The problem is that our repo is a couple of RN versions behind. I've just started working on updating the it to support the latest couple of versions of RN. Step one is getting all of our packages upgraded to more recent versions while still using RN 0.72.x. This'll make it easier to do the next couple of upgrades. If anyone wants to give it a test on a 0.72.x project, that'd be super helpful: https://github.com/rive-app/rive-react-native/pull/267

**Comment by alextoudic** [comment]
I encountered the same issue and have been digging into it. IMO it's not related to React Native version as out-of-the-box, even latest version is working fine with `rive-react-native`

The issue seems to be tied to `use_frameworks! :linkage => :static`, which a lot of people need for `@react-native-firebase`. The crash started happening after [this commit](https://github.com/rive-app/rive-ios/commit/6814254076cfc7e2d5292381f10e9b101ac25db1) in `rive-ios`.

It seems like with static linkage, symbols from Rive’s Yoga fork are being exported, which is causing a collision with React Native’s Yoga and leading to that bad access error.

I haven’t found a workaround, and I think this might need to be handled in `rive-runtime` to avoid these collisions

Any thoughts or ideas?

**Comment by lancesnider** [comment]
This should be resolved with 8.2.0. Please let me know if it doesn't work for you. 

## Troubleshooting

- Remove `node_modules` and `ios/Pods` 
- Remove any reference to Rive in `package-lock.json` or `yarn.lock` and run `yarn` or `npm i` again
- Remove any reference to Rive in the `ios/Podfile.lock` and rerun `Pod install`

**Comment by casualWaist** [comment]
I have a similar issue and upgrading to 8.2.0 this morning, following your debug steps, did not work for me.
`-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: EDC90D54-EB97-4FF4-86D5-632AA0FF27BF
CrashReporter Key:   1058575E-487E-DB2F-EFEC-6F6AF59701A6
Hardware Model:      MacBookPro17,1
Process:             Gumball [48806]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/8EE356B0-D85E-40B8-88CA-4EE6F9E77352/data/Containers/Bundle/Application/E49AE925-DB12-4D4C-9C6C-A5012DBC84F6/Gumball.app/Gumball
Identifier:          ai.gumballapp.gumball
Version:             0.1.1 (2)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [16709]
Coalition:           com.apple.CoreSimulator.SimDevice.8EE356B0-D85E-40B8-88CA-4EE6F9E77352 [226006]
Responsible Process: SimulatorTrampoline [95609]

Date/Time:           2024-11-28 10:44:43.9377 -0500
Launch Time:         2024-11-28 10:44:41.7928 -0500
OS Version:          macOS 15.0.1 (24A348)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000104100
Exception Codes: 0x0000000000000001, 0x0000000000104100
VM Region Info: 0x104100 is not in any region.  Bytes before following region: 4362780416
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      1041b0000-1041b4000    [   16K] r-x/r-x SM=COW  /Users/USER/Library/Developer/CoreSimulator/Devices/8EE356B0-D85E-40B8-88CA-4EE6F9E77352/data/Containers/Bundle/Application/E49AE925-DB12-4D4C-9C6C-A5012DBC84F6/Gumball.app/Gumball
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [48806]

Triggered by Thread:  3

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x104285290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1042966c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10428d3f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x1042855cc mach_msg + 20
4   CoreFoundation                	       0x18041b000 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180415528 __CFRunLoopRun + 1160
6   CoreFoundation                	       0x180414c24 CFRunLoopRunSpecific + 552
7   GraphicsServices              	       0x19020ab10 GSEventRunModal + 160
8   UIKitCore                     	       0x185ad82fc -[UIApplication _run] + 796
9   UIKitCore                     	       0x185adc4f4 UIApplicationMain + 124
10  Gumball.debug.dylib           	       0x1079f8d50 __debug_main_executable_dylib_entry_point + 96 (main.m:7)
11  dyld_sim                      	       0x104361410 start_sim + 20
12  dyld                          	       0x104562274 start + 2840

Thread 1:
0   libsystem_pthread.dylib       	       0x10420a92c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x10420a92c start_wqthread + 0

Thread 3 Crashed::  Dispatch queue: com.facebook.react.ShadowQueue
0   ???                           	          0x104100 ???
1   Gumball.debug.dylib           	       0x1082204c8 -[RCTShadowView layoutWithMinimumSize:maximumSize:layoutDirection:layoutContext:] + 176 (RCTShadowView.m:268)
2   Gumball.debug.dylib           	       0x10820e748 -[RCTRootShadowView layoutWithAffectedShadowViews:] + 264 (RCTRootShadowView.m:35)
3   Gumball.debug.dylib           	       0x1082342d8 -[RCTUIManager uiBlockWithLayoutUpdateForRootView:] + 344 (RCTUIManager.m:549)
4   Gumball.debug.dylib           	       0x108239ff0 -[RCTUIManager _layoutAndMount] + 336 (RCTUIManager.m:1126)
5   Gumball.debug.dylib           	       0x108239e94 -[RCTUIManager batchDidComplete] + 32 (RCTUIManager.m:1109)
6   Gumball.debug.dylib           	       0x108187db8 __32-[RCTCxxBridge batchDidComplete]_block_invoke + 56 (RCTCxxBridge.mm:1514)
7   libdispatch.dylib             	       0x1801774ec _dispatch_call_block_and_release + 24
8   libdispatch.dylib             	       0x180178de0 _dispatch_client_callout + 16
9   libdispatch.dylib             	       0x180180f60 _dispatch_lane_serial_drain + 956
10  libdispatch.dylib             	       0x180181a98 _dispatch_lane_invoke + 388
11  libdispatch.dylib             	       0x18018cf44 _dispatch_root_queue_drain_deferred_wlh + 276
12  libdispatch.dylib             	       0x18018c5a0 _dispatch_workloop_worker_thread + 440
13  libsystem_pthread.dylib       	       0x10420bb74 _pthread_wqthread + 284
14  libsystem_pthread.dylib       	       0x10420a934 start_wqthread + 8

Thread 4:
0   libsystem_pthread.dylib       	       0x10420a92c start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x10420a92c start_wqthread + 0

Thread 6:: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib        	       0x104285290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1042966c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10428d3f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x1042855cc mach_msg + 20
4   CoreFoundation                	       0x18041b000 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180415528 __CFRunLoopRun + 1160
6   CoreFoundation                	       0x180414c24 CFRunLoopRunSpecific + 552
7   Foundation                    	       0x180f319c8 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 208
8   Foundation                    	       0x180f31be8 -[NSRunLoop(NSRunLoop) runUntilDate:] + 60
9   UIKitCore                     	       0x185b858c0 -[UIEventFetcher threadMain] + 404
10  Foundation                    	       0x180f58810 __NSThread__start__ + 720
11  libsystem_pthread.dylib       	       0x10420f6f8 _pthread_start + 104
12  libsystem_pthread.dylib       	       0x10420a940 thread_start + 8

Thread 7:
0   libsystem_pthread.dylib       	       0x10420a92c start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	       0x10420a92c start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib       	       0x10420a92c start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib       	       0x10420a92c start_wqthread + 0

Thread 11:
0   libsystem_pthread.dylib       	       0x10420a92c start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib       	       0x10420a92c start_wqthread + 0

Thread 13:
0   libsystem_pthread.dylib       	       0x10420a92c start_wqthread + 0

Thread 14:
0   libsystem_pthread.dylib       	       0x10420a92c start_wqthread + 0

Thread 15:
0   libsystem_pthread.dylib       	       0x10420a92c start_wqthread + 0

Thread 16:
0   libsystem_pthread.dylib       	       0x10420a92c start_wqthread + 0

Thread 17:: com.facebook.SocketRocket.NetworkThread
0   libsystem_kernel.dylib        	       0x104285290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1042966c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10428d3f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x1042855cc mach_msg + 20
4   CoreFoundation                	       0x18041b000 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180415528 __CFRunLoopRun + 1160
6   CoreFoundation                	       0x180414c24 CFRunLoopRunSpecific + 552
7   Foundation                    	       0x180f319c8 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 208
8   Gumball.debug.dylib           	       0x10864a194 -[SRRunLoopThread main] + 260 (SRRunLoopThread.m:71)
9   Foundation                    	       0x180f58810 __NSThread__start__ + 720
10  libsystem_pthread.dylib       	       0x10420f6f8 _pthread_start + 104
11  libsystem_pthread.dylib       	       0x10420a940 thread_start + 8

Thread 18:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	       0x104285290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1042966c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10428d3f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x1042855cc mach_msg + 20
4   CoreFoundation                	       0x18041b000 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180415528 __CFRunLoopRun + 1160
6   CoreFoundation                	       0x180414c24 CFRunLoopRunSpecific + 552
7   CFNetwork                     	       0x1849d62b0 +[__CFN_CoreSchedulingSetRunnable _run:] + 372
8   Foundation                    	       0x180f58810 __NSThread__start__ + 720
9   libsystem_pthread.dylib       	       0x10420f6f8 _pthread_start + 104
10  libsystem_pthread.dylib       	       0x10420a940 thread_start + 8

Thread 19:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	       0x10428f700 __select + 8
1   CoreFoundation                	       0x180429a48 __CFSocketManager + 676
2   libsystem_pthread.dylib       	       0x10420f6f8 _pthread_start + 104
3   libsystem_pthread.dylib       	       0x10420a940 thread_start + 8

Thread 20:: com.facebook.react.JavaScript
0   libobjc.A.dylib               	       0x180065e8c objc_release + 24
1   libobjc.A.dylib               	       0x18008ddbc AutoreleasePoolPage::releaseUntil(objc_object**) + 212
2   libobjc.A.dylib               	       0x18008dc80 objc_autoreleasePoolPop + 256
3   Gumball.debug.dylib           	       0x1081d1934 invocation function for block in facebook::react::RCTMessageThread::runAsync(std::__1::function<void ()>) + 56 (RCTMessageThread.mm:45)
4   CoreFoundation                	       0x18041b58c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
5   CoreFoundation                	       0x18041acc4 __CFRunLoopDoBlocks + 352
6   CoreFoundation                	       0x1804153cc __CFRunLoopRun + 812
7   CoreFoundation                	       0x180414c24 CFRunLoopRunSpecific + 552
8   Gumball.debug.dylib           	       0x10817a398 +[RCTCxxBridge runRunLoop] + 736 (RCTCxxBridge.mm:326)
9   Foundation                    	       0x180f58810 __NSThread__start__ + 720
10  libsystem_pthread.dylib       	       0x10420f6f8 _pthread_start + 104
11  libsystem_pthread.dylib       	       0x10420a940 thread_start + 8

Thread 21:: hades
0   libsystem_kernel.dylib        	       0x10428872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x10420fc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030329c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   hermes                        	       0x10540d908 hermes::vm::HadesGC::Executor::worker() + 112
4   hermes                        	       0x10540d86c void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, hermes::vm::HadesGC::Executor::Executor()::'lambda'()>>(void*) + 44
5   libsystem_pthread.dylib       	       0x10420f6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x10420a940 thread_start + 8

Thread 22:: com.apple.CFNetwork.CustomProtocols
0   libsystem_kernel.dylib        	       0x104285290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1042966c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10428d3f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x1042855cc mach_msg + 20
4   CoreFoundation                	       0x18041b000 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180415528 __CFRunLoopRun + 1160
6   CoreFoundation                	       0x180414c24 CFRunLoopRunSpecific + 552
7   CFNetwork                     	       0x1849d62b0 +[__CFN_CoreSchedulingSetRunnable _run:] + 372
8   Foundation                    	       0x180f58810 __NSThread__start__ + 720
9   libsystem_pthread.dylib       	       0x10420f6f8 _pthread_start + 104
10  libsystem_pthread.dylib       	       0x10420a940 thread_start + 8

Thread 23:: com.apple.CFStream.LegacyThread
0   libsystem_kernel.dylib        	       0x104285290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1042966c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10428d3f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x1042855cc mach_msg + 20
4   CoreFoundation                	       0x18041b000 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180415528 __CFRunLoopRun + 1160
6   CoreFoundation                	       0x180414c24 CFRunLoopRunSpecific + 552
7   CoreFoundation                	       0x1804393cc _legacyStreamRunLoop_workThread + 260
8   libsystem_pthread.dylib       	       0x10420f6f8 _pthread_start + 104
9   libsystem_pthread.dylib       	       0x10420a940 thread_start + 8


Thread 3 crashed with ARM Thread State (64-bit):
    x0: 0x0000000104e1d190   x1: 0x0000000000104100   x2: 0x000000007f8f0f0f   x3: 0x000000016bd61f90
    x4: 0x0000000000000004   x5: 0x0000000000000000   x6: 0x0000000000000072   x7: 0x0000000000000000
    x8: 0x00000000000000a4   x9: 0x0000000000000004  x10: 0x00000001081cbf0c  x11: 0x0000000000000001
   x12: 0x0000000020000001  x13: 0x0000000100000000  x14: 0x0000000100000000  x15: 0x0000000300000000
   x16: 0x0000000104b877b0  x17: 0x0000000108220418  x18: 0x0000000000000000  x19: 0x0000000104e1d190
   x20: 0x000000007fc00000  x21: 0x0000000000000114  x22: 0x0000000000000004  x23: 0x0000000000000000
   x24: 0x0000600002c23b68  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000600001795680
   x28: 0x0000000000000000   fp: 0x000000016bd61d10   lr: 0x0000000104b85560
    sp: 0x000000016bd61d00   pc: 0x0000000000104100 cpsr: 0x20001000
   far: 0x0000000000104100  esr: 0x82000006 (Instruction Abort) Translation fault

Binary Images:
       0x10455c000 -        0x1045dffff dyld (*) <40bedd20-da23-3b70-a9c2-a1c68a738762> /usr/lib/dyld
       0x1041b0000 -        0x1041b3fff ai.gumballapp.gumball (0.1.1) <96624ce5-0e84-33fd-8fc5-885c3ed0d7d4> /Users/USER/Library/Developer/CoreSimulator/Devices/8EE356B0-D85E-40B8-88CA-4EE6F9E77352/data/Containers/Bundle/Application/E49AE925-DB12-4D4C-9C6C-A5012DBC84F6/Gumball.app/Gumball
       0x104360000 -        0x1043a3fff dyld_sim (*) <e3f44485-3ed0-37c0-a68c-d2e246261b3d> /Volumes/VOLUME/*/dyld_sim
       0x1079f4000 -        0x108a0ffff Gumball.debug.dylib (*) <6e76a2e0-7e71-3fe4-92fa-1f717249a3c3> /Users/USER/Library/Developer/CoreSimulator/Devices/8EE356B0-D85E-40B8-88CA-4EE6F9E77352/data/Containers/Bundle/Application/E49AE925-DB12-4D4C-9C6C-A5012DBC84F6/Gumball.app/Gumball.debug.dylib
       0x1049c4000 -        0x104bf3fff rive.app.ios.runtime.RiveRuntime (6.3.7) <67428627-1ac4-3004-9a59-15d549a7f274> /Users/USER/Library/Developer/CoreSimulator/Devices/8EE356B0-D85E-40B8-88CA-4EE6F9E77352/data/Containers/Bundle/Application/E49AE925-DB12-4D4C-9C6C-A5012DBC84F6/Gumball.app/Frameworks/RiveRuntime.framework/RiveRuntime
       0x1052a8000 -        0x1055affff dev.hermesengine.iphonesimulator (0.12.0) <ea044ee8-b56e-358b-b374-73e2a5d1e031> /Users/USER/Library/Developer/CoreSimulator/Devices/8EE356B0-D85E-40B8-88CA-4EE6F9E77352/data/Containers/Bundle/Application/E49AE925-DB12-4D4C-9C6C-A5012DBC84F6/Gumball.app/Frameworks/hermes.framework/hermes
       0x104264000 -        0x10426bfff libsystem_platform.dylib (*) <cac022b0-a3f8-30b6-8328-16b8f49134fc> /usr/lib/system/libsystem_platform.dylib
       0x104284000 -        0x1042bffff libsystem_kernel.dylib (*) <259ab955-09a7-3260-9fd3-c44d68acbe05> /usr/lib/system/libsystem_kernel.dylib
       0x104208000 -        0x104217fff libsystem_pthread.dylib (*) <a7b14a67-6701-3dd4-b1ca-738197b71fb0> /usr/lib/system/libsystem_pthread.dylib
       0x1041ec000 -        0x1041f7fff libobjc-trampolines.dylib (*) <9d7046dc-1d3a-38e2-8c09-5390b17983ed> /Volumes/VOLUME/*/libobjc-trampolines.dylib
       0x18038b000 -        0x180758fff com.apple.CoreFoundation (6.9) <abfb49cc-2cd7-3604-8da3-d0f36eeba2d9> /Volumes/VOLUME/*/CoreFoundation.framework/CoreFoundation
       0x190207000 -        0x19020ffff com.apple.GraphicsServices (1.0) <879db49d-67e9-3711-86de-5fd83519cf32> /Volumes/VOLUME/*/GraphicsServices.framework/GraphicsServices
       0x184ca0000 -        0x1869a4fff com.apple.UIKitCore (1.0) <f8f442f5-7a9e-3765-9a2a-8c38238155f1> /Volumes/VOLUME/*/UIKitCore.framework/UIKitCore
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x180175000 -        0x1801b9fff libdispatch.dylib (*) <76a67435-58c9-3af9-9d46-02ab7161baeb> /Volumes/VOLUME/*/libdispatch.dylib
       0x1807d8000 -        0x181428fff com.apple.Foundation (6.9) <d10a658f-43ab-384f-b207-60969a8b5b45> /Volumes/VOLUME/*/Foundation.framework/Foundation
       0x1847ce000 -        0x184b4dfff com.apple.CFNetwork (1.0) <51e6fb9c-4ce4-36ab-8a25-77c4b96aa7eb> /Volumes/VOLUME/*/CFNetwork.framework/CFNetwork
       0x180064000 -        0x18009fd53 libobjc.A.dylib (*) <f8c15bc7-b4df-3cf9-b06e-18f023382985> /Volumes/VOLUME/*/libobjc.A.dylib
       0x1802e3000 -        0x180365ff3 libc++.1.dylib (*) <beef6d56-dcd9-3b42-a93e-eb3a731c4dc0> /Volumes/VOLUME/*/libc++.1.dylib

EOF

-----------
Full Report
-----------`
 using expo 51.0.38 and RN 0.74.5

**Comment by Maniae** [comment]
Still having the same issue  (EXC_BAD_ACCESS) on 8.2.0 (runtime 6.3.7)

**Comment by lancesnider** [comment]
Sorry @casualWaist  for the false positive on 8.2. I'm just pushing 8.3 to npm now. This one has been tested by a couple of different people with the same issue so I'm confident it'll fix the problem this time. If it doesn't, please let me know.

**Comment by anatoleblanc** [comment]
Hey friends, we are still seeing a bunch of these on 8.3.0 - anything we could try to prevent it?

**Comment by lancesnider** [comment]
@anatoleblanc sorry, I didn't see this because the issue is closed. I know that the error looks the same, but I think this is a new, unrelated problem. Can you please create a new issue.
