### ISSUE TITLE
glitching

### ISSUE THREAD

**Issue by leemhenson** [rive-app/rive-react-native#283]
### Description
When Rive is running in the simulator through metro, and you leave the simulator. When you return you get weird artifacts appearing on the screen until the app is reloaded. Once reloaded, it's fine.

### Provide a Repro
https://github.com/user-attachments/assets/12b2ac46-cd4a-4fa6-9093-a08cb40c1a67

The video hasn't caught all of it either, there's actually more similar artifacts appearing on the character underneath the thought bubble. Both of those are two different Rive animation files displayed with `rive-react-native`.

#### Source `.riv`/`.rev` file
Supplied on request.

### Expected behavior
Not to glitch

#### Additional context
RN 0.76/Expo 52, but this was also observed on prior RN/Expo.
Also occurs on the Android simulator.

**Comment by leemhenson** [comment]
We have also now seen the same sort of glitching in a production release of our app, on an Android tablet. So I think it's fair to say whatever causes this glitching occurs much less often in a production build, but it is still there. We see it quite a lot on the simulator, almost always after returning to the app after it's been closed or backgrounded.

**Comment by leemhenson** [comment]
Still glitching with the new 8.5.0 release:

https://github.com/user-attachments/assets/02b7a804-c3b2-4be8-b680-4fdfe9ed3fa2

**Comment by tiago138** [comment]
I am having the same problem, after updating to version 9 on a lg 17+ all animations are broken.

**Comment by Yidaotus** [comment]
Bumping: We also started to see those glitching artifacts. They are not reproducible all the time and not every device seems to be affected. Anyway we can help to resolve this?

**Comment by tiago138** [comment]
> Bumping: We also started to see those glitching artifacts. They are not reproducible all the time and not every device seems to be affected. Anyway we can help to resolve this?

I went back to the 8.4.0 version that uses the skia render and I don't have the problem anymore, the problem seems to be on the rive render.

It makes no sense that they removed the skia render if the rive render is full of bugs and does not work properly.

**Comment by tslater** [comment]
Seeing it on our end as well. Breaking issue in the app for us. We are seeing it with multiple animations and have had to start removing rive in key areas.

Really hard to reproduce consistently, but it really bad when it happens.
When it does seem to happen more when the app is backgrounded for a while.

Here is a video of glitching + artifact. Happening on 2 other animations as well:
https://github.com/user-attachments/assets/906385fc-a5a4-4002-b29a-beef421ee6ce

**Comment by tslater** [comment]
I should add, this is NOT just on the simulator. It happens on devices on production builds. For us it happens MORE on devices than the simulator.

**Comment by tiago138** [comment]
Guys I am stating to think this project is dead, this is a serious problem but no one from the team said anything about it.

I am getting worried.

**Comment by tslater** [comment]
I think it's hard for the Rive folks to maintain so many platforms (Android, iOS, Flutter, Unity, etc.). We've mostly accepted the fact that RN is a lower priority and that makes some sense.

The thing about this issue is I think it is a bug with the RiveRenderer implementation for iOS itself, meaning not an RN specific issue.

 I'm debating if I should try to reproduce on a native iOS project and create an issue there. The trouble is that it doesn't seem to happen my my phone very often, just on customers. Typical right?

Does anyone have an animation or a setup where this happens 100% of the time?

@leemhenson @tiago138 ?

**Comment by tslater** [comment]
@HayesGordon  is this on your radar at all?

**Comment by abhikm500** [comment]
Bumping this up, we're facing the same kind of glitching as above.

**Comment by leemhenson** [comment]
> I think it is a bug with the RiveRenderer implementation for iOS itself

It also occurs on Android.

> Does anyone have an animation or a setup where this happens 100% of the time?

No, but it occurs more often while running the app in Metro. There's something about foregrounding the app after it's been in the background for a while that also seems to contribute.

**Comment by tiago138** [comment]
@tslater On my old lg q7+ it happens 100% of the time with all the animations.

**Comment by tslater** [comment]
So Android too? we're only seeing it on iOS right now. What android version is that?

**Comment by iamrestrepo** [comment]
Also having this glitching issue with my app, at starting time mainly but also across some screen intermittently. Would really help if this gets solved!

**Comment by tiago138** [comment]
@tslater the Android version is 8.1.0 later I will send a video.

**Comment by garfieldnate** [comment]
We are hitting this as well and having to back out of rive for some animations, which is both a shame and an unfortunate loss of resources. Please let me know if I can help in any way! I'm willing to pitch in but don't know where to start.

**Comment by bpthu123** [comment]
Also seeing this issue; need help to resolve

**Comment by tiago138** [comment]
@tslater all the animations in the app are behaving like that.
https://github.com/user-attachments/assets/7e5ab761-ad99-45e0-832c-6f32df156fee

**Comment by HayesGordon** [comment]
Thanks for all the reports; this helps us prioritize this issue. I want to address your concerns: this project is not dead!

For the future, if you strongly believe that the core issue is rendering-related, you're welcome to also file a report on our native iOS and Android repositories to get additional eyes on it.

Our rendering team is investigating a known issue on certain Android devices that is causing a glitch that may relate to the above.

Seeing as this thread has many reports mentioning various different versions and devices used, it'll be helpful if we can get a reproducible sample that uses the **latest version** of the current Rive Runtime, which:
- Ideally includes a full project we can run (if it's tied to other project settings or only occurs after some condition)
- The .riv file causing the issue with information on which artboard/state triggers it
- Detailed information on the device + hardware that is causing the glitch. This is especially important for Android, as one device's GPU may require a different workaround than another.

I'd also like to point out that we did remove Skia. However, we still provide a fallback renderer to the native platform:
- iOS via CoreGraphics
- Android via Canvas

You can find more information on using those renderers [here](https://rive.app/docs/runtimes/choose-a-renderer/overview#specifying-a-renderer). Note that:
- These renderers do not support vector feathering
- Performance should be tested when using these renderers

If you're observing these issues on these native renderers as well, then that would be good information to have, as that would indicate that something else is causing the issues.

**Comment by tiago138** [comment]
@HayesGordon you can use this repo to check the error.

rive-react-native 9.2.0
Device LG Q7+
Android 8.1.0

https://github.com/tiago138/rive-error

If you need any other let me know.

**Comment by HayesGordon** [comment]
> [@HayesGordon](https://github.com/HayesGordon) you can use this repo to check the error.
> 
> The problem happens as soon as the app start.
> 
> rive-react-native 9.2.0 Device LG Q7+ Android 8.1.0
> 
> https://github.com/tiago138/rive-error
> 
> If you need any other info let me know.

Thanks @tiago138, we're about to make an Android release that fixes rendering glitches. This may resolve your issue as well.

I'll post here when that is released, and I'll ask you if you can verify if it's resolved. If not, I'll escalate this to the rendering team, as it may require us procuring this specific device first.

**Comment by HayesGordon** [comment]
> > [@HayesGordon](https://github.com/HayesGordon) you can use this repo to check the error.
> > The problem happens as soon as the app start.
> > rive-react-native 9.2.0 Device LG Q7+ Android 8.1.0
> > https://github.com/tiago138/rive-error
> > If you need any other info let me know.
> 
> Thanks [@tiago138](https://github.com/tiago138), we're about to make an Android release that fixes rendering glitches. This may resolve your issue as well.
> 
> I'll post here when that is released, and I'll ask you if you can verify if it's resolved. If not, I'll escalate this to the rendering team, as it may require us procuring this specific device first.

We released version 9.2.1, this may address some of the issues mentioned here. If it does not, see the above steps towards providing us a reproducible sample and list which devices are causing the issue.

**Comment by tiago138** [comment]
@HayesGordon thanks for the reply.
After testing the version 9.2.1 the problems persists.

**Comment by HayesGordon** [comment]
> [@HayesGordon](https://github.com/HayesGordon) thanks for the reply. After testing the version 9.2.1 the problems persists.

Thanks @tiago138, I'll escalate this issue to the rendering team - this may take some time if it requires procuring a specific testing device. Just out of curiosity, did you try with Canvas as a renderer?

**Comment by tiago138** [comment]
> > [@HayesGordon](https://github.com/HayesGordon) thanks for the reply. After testing the version 9.2.1 the problems persists.
> 
> Thanks [@tiago138](https://github.com/tiago138), I'll escalate this issue to the rendering team - this may take some time if it requires procuring a specific testing device. Just out of curiosity, did you try with Canvas as a renderer?

Using the Canvas render I have the same issue.
But I think the option is not working because with the version 8.4.0 it works fine with all the renders.

I am puttin it on my top layout

```tsx
 useEffect(() => {
    RiveRenderer.defaultRenderer(
      RiveRendererIOS.Rive,
      RiveRendererAndroid.Rive
    );
  }, []);
```

**Comment by HayesGordon** [comment]
> > > [@HayesGordon](https://github.com/HayesGordon) thanks for the reply. After testing the version 9.2.1 the problems persists.
> > 
> > 
> > Thanks [@tiago138](https://github.com/tiago138), I'll escalate this issue to the rendering team - this may take some time if it requires procuring a specific testing device. Just out of curiosity, did you try with Canvas as a renderer?
> 
> Using the Canvas render I have the same issue. But I think the option is not working because with the version 8.4.0 it works fine with all the renders.
> 
> I am puttin it on my top layout
> 
>  useEffect(() => {
>     RiveRenderer.defaultRenderer(
>       RiveRendererIOS.Rive,
>       RiveRendererAndroid.Rive
>     );
>   }, []);

Thanks for taking a look. You need to change `RiveRendererAndroid.Rive` to `RiveRendererAndroid.Canvas`, the default is the RiveRenderer, and I want to rule out if it is also not working when using Canvas.

**Comment by HayesGordon** [comment]
> [@HayesGordon](https://github.com/HayesGordon) ,
> 
> Here is a MCVE: https://github.com/wordscenes/rive-mcve.
> 
> Pretty sure it will happen on any iOS device, so should be much easier to reproduce than buying an old android phone.
> 
> The ones we've tested in include:
> 
> * iPhone 14 Pro max (iOS 18.4)
> * iPhone SE 3rd Gen (iOS 13.2 ) Simulator
> * iPhone 16 Pro Max (iOS 18.2) Simulator
> 
> We are pretty confident we're seeing it with a single animation at a time, but it only happens occasionally and is hard to reproduce. When we add both animations it is happening 100% of the time.
> 
>  Simulator.Screen.Recording.-.iPhone.16.Pro.Max.-.2025-04-04.at.13.19.51.mp4

@tslater thanks for the info. I tried on three simulators and was not able to reproduce. If you're able to test on any of the below simulators to verify if it's still happening for you that would be helpful.

I'm currently stuck on XCode 15 and can't get any of these simulators, but can ask other members on the team to test the above simulators, or the specific physical device.

Other questions:
- Are you using an Intel Mac or are you on the M architecture?
- Can you ensure you're using the latest version of Rive on iOS: `cd ios` and `pod update RiveRuntime`

https://github.com/user-attachments/assets/6831d633-e449-4541-a044-7afdc6103fa2

https://github.com/user-attachments/assets/39b80acb-8946-44c8-bac9-f45a87176232

https://github.com/user-attachments/assets/41750c6d-d933-43a7-abf2-12cdf6794473

**Comment by tiago138** [comment]
> > > > [@HayesGordon](https://github.com/HayesGordon) thanks for the reply. After testing the version 9.2.1 the problems persists.
> > > 
> > > 
> > > Thanks [@tiago138](https://github.com/tiago138), I'll escalate this issue to the rendering team - this may take some time if it requires procuring a specific testing device. Just out of curiosity, did you try with Canvas as a renderer?
> > 
> > 
> > Using the Canvas render I have the same issue. But I think the option is not working because with the version 8.4.0 it works fine with all the renders.
> > I am puttin it on my top layout
> > useEffect(() => {
> > RiveRenderer.defaultRenderer(
> > RiveRendererIOS.Rive,
> > RiveRendererAndroid.Rive
> > );
> > }, []);
> 
> Thanks for taking a look. You need to change `RiveRendererAndroid.Rive` to `RiveRendererAndroid.Canvas`, the default is the RiveRenderer, and I want to rule out if it is also not working when using Canvas.

I changed it to RiveRendererAndroid.Canvas on the 9.2.1 version.
But on the 8.4.0 using RiveRendererAndroid.Rive it works with no problems.

**Comment by tiago138** [comment]
@HayesGordon maybe this issue on the rive-android repo is related.
https://github.com/rive-app/rive-android/issues/361

**Comment by Yidaotus** [comment]
> > > [@HayesGordon](https://github.com/HayesGordon) ,
> > > Here is a MCVE: https://github.com/wordscenes/rive-mcve.
> > > Pretty sure it will happen on any iOS device, so should be much easier to reproduce than buying an old android phone.
> > > The ones we've tested in include:
> > > 
> > > * iPhone 14 Pro max (iOS 18.4)
> > > * iPhone SE 3rd Gen (iOS 13.2 ) Simulator
> > > * iPhone 16 Pro Max (iOS 18.2) Simulator
> > > 
> > > We are pretty confident we're seeing it with a single animation at a time, but it only happens occasionally and is hard to reproduce. When we add both animations it is happening 100% of the time.
> > > Simulator.Screen.Recording.-.iPhone.16.Pro.Max.-.2025-04-04.at.13.19.51.mp4
> > 
> > 
> > [@tslater](https://github.com/tslater) thanks for the info. I tried on three simulators and was not able to reproduce. If you're able to test on any of the below simulators to verify if it's still happening for you that would be helpful.
> > I'm currently stuck on XCode 15 and can't get any of these simulators, but can ask other members on the team to test the above simulators, or the specific physical device.
> > Other questions:
> > 
> > * Are you using an Intel Mac or are you on the M architecture?
> > * Can you ensure you're using the latest version of Rive on iOS: `cd ios` and `pod update RiveRuntime`
> > 
> > CleanShot.2025-04-04.at.15.16.34.mp4
> > CleanShot.2025-04-04.at.14.32.51.mp4
> > CleanShot.2025-04-04.at.14.35.42.mp4
> 
> That is pretty strange that you are not seeing it. I tested 2/3 of those simulators and am still seeing the glitch: https://github.com/user-attachments/assets/53326fa2-b083-4122-a482-61fa9bdfe3d1 https://github.com/user-attachments/assets/5ef10a20-93e9-4581-81aa-7b916909e1e2
> 
> I'm on a Apple M4 Max, Sequoia 15.2.
> 
> I can confirm I'm on the latest RiveRuntime.
> 
> I'm scratching my head on what the difference is??

Since I also have issues with glitching I tested this MCVE and I was able to reproduce the glitching too!
I'm on a Apple M4 Max, 15.4 with:

* IPhone 16 Pro (iOS 18.2, Simulator)
* IPhone 16 Pro Max (iOS 18.4)

@HayesGordon where you, or other members, able to reproduce this with any of those devices?

**Comment by tslater** [comment]
I was so excited that I finally could get this but to reproduce reliably. It's been glitching for me 100% of the time for several days now. I had a teammate try it and it was not glitching for them on any simulator even though their mac is very similar. I commented out the animations one at a time and it stopped glitching. I reset the code back and now I cannot get it to glitch no matter what I do. I restart metro, rebuild, etc. No simulator will gltich. I am really lost here. This is very frustrating because it breaks our app. We have over 1M downloads and get a handful of complains per week about it, sometimes multiple a day. I really hope we can figure out a more reliable way to reproduce it soon.

**Comment by tslater** [comment]
@HayesGordon Can you try just re-opening the app lots of times? It used to happen 100% of the time, but now it is less reliable but does happen sometimes when you first open the app. Check out the video of me repeatedly opening and closing.

https://github.com/user-attachments/assets/72c02060-d691-46c9-b6f1-c69ff1b0c1fa

**Comment by tslater** [comment]
@HayesGordon 
Ok, I _think_ I finally have a way to reproduce it 100% of the time. I had a teammate who initially told me they couldn't reproduce it and now they can do it every time to.

Here are the steps:
1. Make sure your metro server is **NOT** running
2. Open the dev client
3. Start metro server
4. Select metro server from the dev client (refresh if it isn't listed)
5. Experience the _glitch_

Here is a link to download the exact dev client I'm using:
https://cdn.discordapp.com/attachments/1295449969578344458/1359566390318858400/build-1744216103980.tar.gz?ex=67f7f25e&is=67f6a0de&hm=75125f23802345d7c921f469774a9ee010d9ba65a0c891164df32cfcd9c848cc&

I created the dev client by running this in the project*: 
```eas build --platform ios --profile simulator --local``` 

***I added the simulator profile recently so you'll have to pull in order for that command to work**

Here's a video running the steps:

https://github.com/user-attachments/assets/fe7508b7-5f90-4f73-9fbf-48da65e3464e

To be clear this happens in production too. It's just hard to reproduce. It seems to correlate with opening the app straight to an animation, possibly from backgrounding. Some kind of race condition, seems to often involve when there's more than one animation on the screen. It happens with all of our animations. We have >1M downloads and we get multiple negative reviews a week, sometimes multiple a day about this issue.

**Comment by iamrestrepo** [comment]
I wasn't able to reproduce this until I tried these steps and now I get it every time! Hope you guys can fix it soon! 🙏🏼

**Comment by tslater** [comment]
@HayesGordon Do you mind trying this out and seeing if you can reproduce as well?

**Comment by tslater** [comment]
We're finding that animations don't work at all on a lot of android devices on the latest RN-rive. Also on the https://github.com/wordscenes/rive-mcve. 

Here's one device example, will add more:
One Plus 7 Pro
Android Version: 11
Modell: GM1913

**Comment by tslater** [comment]
@HayesGordon Could we get another look at this? It's a very serious issue affecting our users.

**Comment by HayesGordon** [comment]
Thanks all, we'll try again to get this reproducing as soon as possible, and escalate to our rendering team

**Comment by lancesnider** [comment]
@tslater It looks like the link is down.

**Comment by tslater** [comment]
Here's a new link:
https://drive.google.com/file/d/1jKJCDyaHXQSRNAxGHm-gudyDPp--IWWL/view?usp=sharing

I am pretty confident you won't need it. They key here is to use the steps above. We've been able to reproduce on several different setups using that. It seems to be related to how the app loads, and having > 1 animation on the screen.

**Comment by garfieldnate** [comment]
I hate to prod as well but this is actually a pretty serious blocker for us, as well 😅 . Please let us know if we can assist with anything here to help expedite the process.

**Comment by lancesnider** [comment]
Sorry this one has been so hard to track down. I thought we fixed up the latest rendering issues with 9.2.1. Can anyone share a simple github repo where this is happening? Or if it's just a default expo setup, could you send me a .rev?

**Comment by tslater** [comment]
@lancesnider 

We posted one earlier Spent many hours trying to get a reliable reproduction.

Here's our code:
  https://github.com/wordscenes/rive-mcve.

Here are the steps:

1. Make sure your metro server is NOT running
2. Open the dev client in any iOS simulator (we tried quite a few)
3. Start metro server
4. Select metro server from the dev client (refresh if it isn't listed)

Then you can see the glitch every time


I'm fairly confident this will happen any time you have 2 Rive animations on the screen and follow these steps.

To be clear, we see it in production, without metro server. This is just the one way I know how to reproduce it 100% of the time. I tested with multiple setups with multiple team members.

If it's not working for you, can we jump on a screenshare? I think I can get it for you.

**Comment by lancesnider** [comment]
Thanks, I can reproduce this immediately now with a simple `yarn ios`. Mine is a 16 Pro with iOS 18.1.

**Comment by tslater** [comment]
@lancesnider Glad to hear it! Let me know if we can help in any other way.

**Comment by mehtaabhi248** [comment]
Hey @lancesnider, facing the same issue. Wondering if there’s any update on this!

**Comment by iamrestrepo** [comment]
👋🏼  I had a reminder to check back on this. This is affecting live users 😿 . It would be awesome if this gets solved soon 🤞🏼

**Comment by christophemenager** [comment]
I have the same issue, I know it does not help but I feel this issue should be top prio

**Comment by schedulesmasher** [comment]
We're having to replace Rive until this is fixed.

**Comment by iamrestrepo** [comment]
👋🏼  @HayesGordon , Do you know if there is any work being done on this? I agree on the importance of fixing this sooner vs later. It really downgrades the experience for app users  😢

**Comment by tslater** [comment]
We're getting bad reviews in the app/play store and complaints from users. Would be nice to know if this is actively being work on or not.

**Comment by bpthu123** [comment]
Likewise, we'll have to abandon Rive if this is not fixed. Please help fix this ASAP.

**Comment by christophemenager** [comment]
Same here, this issue is starting to be critical. I love rive, but I would love **transparency** from the Rive team about how they plan to invest on this package in the future.

I have the feeling that react-native is kind of their least priority:

- this issue is critical and has been open for 6 months
- This lib is not compatible with react-native 0.77 released 4 months ago: https://github.com/rive-app/rive-react-native/issues/286
- This lib does not support new architecture which is being rolled out for a long time now, and work did not even start to support it: https://github.com/rive-app/rive-react-native/issues/190
- Features parity is far to be reached compared to native dependencies

I get that this lib is open-source and this implies we can't demand anything @HayesGordon and I am thankful for hole the work you have done so far 🙏

**I'm simply hoping for more transparency regarding the internal roadmap for this library at Rive. This would help businesses that rely on your platform make informed decisions about whether to continue or explore other options.**

**Comment by tslater** [comment]
This lib is open source, but we are paying customers. We've worked around simple RN specific issues but this seems like something beyond that scope, like related to the renderer, otherwise I would roll up my sleeves and get it fixed. With this, we just feel beholden and I'm honestly defending Rive to our dev team. Design is pushing for it, but our devs have lost trust and feel nervous investing more of our UI on Rive.

**Comment by christophemenager** [comment]
FYI latest release `9.3.0` is not fixing this issue

**Comment by Ariannamu** [comment]
Can we get an update on this?

**Comment by tslater** [comment]
@HayesGordon We really appreciate the communication. I will run a test on the test repo to see if downgrading helps. Please keep us in the loop on the renderer issue. Is there an open issue in another repo for it yet? Can you tag it here so we can follow that one?

I talked to our team and our feedback would be to only fix very critical bugs (i.e. this one). We can wait for databinding etc. In fact, we're shy about new features given these issues. Given the lack of resources for React Native, we would vote to limit resources on the current version to just catastrophic issues like this one.

**Comment by christophemenager** [comment]
Thanks for your answer @HayesGordon 🙏

I am 100% aligned with @tslater, and even if it can sound a bit harsh, but "Adding new core Rive features" feels like a waste of time compared to fixing severe issues like this one or adding new architecture. What's the point of adding new features to a lib that does not work and where many people are thinking about leaving Rive? From my point of view it sends the wrong message :/ 

Given the fact that your team has a limited bandwidth on RN, I would focus only on fixing issues, no new feature at all, and moving on with the new architecture.

**Comment by HayesGordon** [comment]
Thanks for the feedback all. Curios @christophemenager with the statement "does not work" - are you referring to this issue or other breaking issues after updating to the latest expo?

Keep in mind that not all Rive users are on the latest version of React Native, and are using Rive React Native successfully in their environment (not saying there aren't issues, we know there is). For other customers adding features such as Data Binding are more important than rewriting the whole package which might require a significant time investment for them (and us) to update to.

Issues such as this one (glitching) is also at a much lower rendering level. Keep in mind that the effort to rewrite this package, the effort to maintain this package, the effort to maintain the native iOS and Android package, and the effort to fix runtime and rendering issues, are all at different levels and require effort from different team members at Rive.

Regarding Data Binding, the work is already completed for React Native (see above link) and we purposely made the decision to expose Data Binding for React Native in a more limited capacity to save time and invest that into the rewrite.

**Comment by christophemenager** [comment]
@HayesGordon I was referring to this issue, which may be exaggerated as you mentioned workarounds in your last comment, but could still be a blocker for many of us (reducing performances may not be an option depending on the use case for example).

Happy to help you beta-test the new lib and thanks again for the communication 🙏

**Comment by tslater** [comment]
@lancesnider I just updated to `rive-react-native@9.3.0`. I deleted the entire ios dir, including all pod-related files, and rebuilt. Still have the glitch. 

I am pretty confident we can get if on your machine again if you want to meet up virtually.

Have you made any progress in identifying the underlying issue. Do we know if this is affecting other platforms?

**Comment by tslater** [comment]
Are there any other issues we can follow in other repos with the core renderer?

**Comment by tslater** [comment]
@lancesnider I filled it out with my calendar link. Looks like more of a generic ticket than a DM link?

**Comment by evelant** [comment]
Possibly related to https://github.com/rive-app/rive-react-native/issues/279

I agree with others here that focus should be on fixing bugs, not new features. My team is pretty unhappy with me at the moment for choosing Rive because of the number of glitches/crashes which have cost us a lot of time and user goodwill.

**Comment by lancesnider** [comment]
@evelant Thanks for the feedback. I’m happy to say it’s been a top concern for us as well over the last few months, and continues to be a top priority.

In this time frame we’ve already greatly expanded our testing efforts.

We’ve expanded our golden testing across various runtimes/platforms. Added silver testing to verify rendering commands. Made a commitment that every new feature and bug fix has a companion test suite before releasing. Expanded our current suite of tests on existing features.

As for the issue you mentioned, we were hoping these were the same issues and that when we fixed that one, this one would get fixed as well. Unfortunately, that's appears not to be the case. :(

**Comment by lancesnider** [comment]
Thanks @tslater. I'm sitting with @csmartdalton right now trying to figure this out. We can reproduce your rive-mcve error almost 100% of the time, but when I remove `rive-react-native`, yarn.lock, node_modules, Pods, Podfile.lock then re-add everything with teh latest `rive-react-native`, it works 100% of the time for me. :/ 

@leemhenson Can you confirm that you're still having this issue? 

Can anyone else provide a repo with the latest version of `rive-react-native` that continues to fail?

**Comment by tslater** [comment]
@lancesnider can you commit your changes to a fork I can look at? I think it would just be `yarn.lock` that would change, right?

**Comment by tslater** [comment]
@lancesnider my understanding of your fix is that it's a nondeterministic fix. It's nothing we can apply. Unless I am understanding it wrong. I don't consider that helpful or fixed and I hope you guys aren't thinking that. 

Based on the communication, is it safe to assume this is low priority in your team's eyes? We're considering reverting to video and code-driven animations or maybe even going back to Lottie at this point. We have no confidence this will get fixed in any reasonable timeline and our entire team is chomping at me to remove Rive.

**Comment by christophemenager** [comment]
I could not agree more with @tslater

Dear Rive team:
- You product is great
- We know you are very busy with many other features and libraries
- We know you have separated teams working on the engine, the native lib and the flutter/react native wrappers
- But please please: COMMUNICATE with us ☺️ @lancesnider how can we help? Can you push a fork of the example where you don't reproduce the bug?

**Comment by garfieldnate** [comment]
This is still an absolute blocker for us. @tslater is able to reproduce the issue reliably and has sent a calendar link to @lancesnider. Lance, could you set up a meeting with Tyler to look at the issue together?

**Comment by tiago138** [comment]
Downgrading it to the version 8.4.0 does not solve the issue for you guys?

**Comment by christophemenager** [comment]
@HayesGordon do you think this issue will be fixed with the new architecture re-write you are currently doing?

Correct me if I am wrong, but I understand this will not be the case as this issue is related to the rive renderer and not the JS part of the lib.

In this case, is there a way for you to re-enable the Skia renderer in the re-write you are doing?

Just trying to find solutions for some of your users, as I just realised the new version you work on will be as flawed as the current one if this issue is not solved on the rive-renderer.

**Comment by HayesGordon** [comment]
We have a lead on the issue, and we'll update here once we know more.
